server:
  port: 8008

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/idea_hub_db?characterEncoding=UTF-8&serverTimezone=UTC
    username: ideahub
    password: ideahub
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
#     ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect #mariaDB를 위한 방언

