server:
  port: 8001


spring:
  config:
    activate:
      on-profile: real
  profiles:
    include: real-db
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect #mariaDB를 위한 방언

logging:
  level:
    org.hibernate.SQL: debug
    #org.hibernate.type: trace    #p6spy로 쿼리 본다
