server:
  port: 8001

spring:
  profiles:
    active: local
    group:
     "real1": "real-db"
     "local": "local,local-oauth"


logging:
  level:
    org.hibernate.SQL: debug
    #org.hibernate.type: trace    #p6spy로 쿼리 본다
