

spring:
  profiles:
    active: local
    group:
     "real1": "real-db,real-oauth"
     "local": "local,local-oauth"
     "real2": "deploy-real2,real-db,real-oauth"
     "real3": "deploy-real3,real-db,real-oauth"
  session: #세션 저장소 db로 활용하기 위한 설정ㅓ
    store-type: jdbc


logging:
  level:
    org.hibernate.SQL: debug
#server:
#  port: 8001
