spring:
  server:
    port: 8001

  config:
    activate:
      on-profile: real
  profiles:
    include: real-db
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
#    hibernate:
      #create : 내가가진 엔티티를 모두 drop 후 create -> 이후 애플리케이션 실행
      #create-drop : 내가가진 엔티티를 모두 drop 후 create -> 이후 애플리케이션 실행 ->애플리케이션 종료시점에 다시 drop 해준다
#      ddl-auto: none
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect #mariaDB를 위한 방언

logging:
  level:
    org.hibernate.SQL: debug
    #org.hibernate.type: trace    #p6spy로 쿼리 본다
