server:
  port: 8001

spring:
  profiles:
    active: real
    group:
     "real": "real,real-db"
     "local": "local"

logging:
  level:
    org.hibernate.SQL: debug
    #org.hibernate.type: trace    #p6spy로 쿼리 본다
